"""
pdf_brief.py — Professional PDF brief generator for IA outputs.

Produces a structured 3-section PDF:
  Page 1: Executive Summary (LLM-generated narrative)
  Page 2: Full MCDA Scoring Table (all options x all criteria)
  Page 3: Evidence & Assumptions (provenance payload)

Uses reportlab — pure Python, no system dependencies.
"""

import io
import re
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)

from app.schemas import BriefRequest

# ─── Colour palette ───────────────────────────────────────────────────────────
EU_BLUE       = colors.HexColor("#003399")
EU_BLUE_LIGHT = colors.HexColor("#E8EEF9")
EU_GOLD       = colors.HexColor("#FFCC00")
DARK_GREY     = colors.HexColor("#333333")
MID_GREY      = colors.HexColor("#666666")
LIGHT_GREY    = colors.HexColor("#F5F5F5")
WHITE         = colors.white
GREEN         = colors.HexColor("#1a7a1a")
RED           = colors.HexColor("#cc0000")
AMBER         = colors.HexColor("#cc6600")


def _clean_markdown(text: str) -> str:
    """Remove markdown formatting so it renders as clean text in PDF."""
    # Remove bold/italic markers
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*',     r'\1', text)
    text = re.sub(r'__(.+?)__',     r'\1', text)
    text = re.sub(r'_(.+?)_',       r'\1', text)
    # Remove markdown headers
    text = re.sub(r'^#{1,3}\s+', '', text, flags=re.MULTILINE)
    return text.strip()


def _styles():
    return {
        "title": ParagraphStyle("title", fontSize=20, textColor=EU_BLUE,
                                fontName="Helvetica-Bold", spaceBefore=0,
                                spaceAfter=8, alignment=TA_LEFT),
        "subtitle": ParagraphStyle("subtitle", fontSize=11, textColor=MID_GREY,
                                   fontName="Helvetica", spaceAfter=16,
                                   alignment=TA_LEFT),
        "section": ParagraphStyle("section", fontSize=13, textColor=EU_BLUE,
                                  fontName="Helvetica-Bold", spaceBefore=10,
                                  spaceAfter=6),
        "body": ParagraphStyle("body", fontSize=10, textColor=DARK_GREY,
                               fontName="Helvetica", leading=16,
                               spaceAfter=6, alignment=TA_JUSTIFY),
        "small": ParagraphStyle("small", fontSize=8, textColor=MID_GREY,
                                fontName="Helvetica", leading=12,
                                spaceAfter=4),
        "label": ParagraphStyle("label", fontSize=9, textColor=MID_GREY,
                                fontName="Helvetica-Bold"),
        "preferred": ParagraphStyle("preferred", fontSize=11, textColor=EU_BLUE,
                                    fontName="Helvetica-Bold", spaceBefore=12,
                                    spaceAfter=6),
        "caption": ParagraphStyle("caption", fontSize=8, textColor=MID_GREY,
                                  fontName="Helvetica-Oblique", spaceAfter=12,
                                  spaceBefore=4, alignment=TA_CENTER),
    }


def _score_color(score: float) -> colors.Color:
    if score >= 1.5:   return GREEN
    elif score >= 0.5: return colors.HexColor("#2d7a2d")
    elif score > -0.5: return DARK_GREY
    elif score > -1.5: return AMBER
    else:              return RED


def _quality_color(flag: str) -> colors.Color:
    if flag == "verified": return GREEN
    elif flag in ("proxy", "stale"): return AMBER
    else: return RED


def _on_page(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Header bar
    canvas.setFillColor(EU_BLUE)
    canvas.rect(0, h - 1.8*cm, w, 1.8*cm, fill=1, stroke=0)
    canvas.setFillColor(EU_GOLD)
    canvas.rect(0, h - 1.85*cm, w, 0.05*cm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(1.5*cm, h - 1.1*cm, "EU Impact Assessment Brief")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 1.5*cm, h - 1.1*cm,
                           f"Strategy & Feedback Agent  |  {datetime.now().strftime('%d %b %Y')}")

    # Footer
    canvas.setFillColor(MID_GREY)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(1.5*cm, 0.8*cm,
                      "Generated by the Strategy & Feedback Agent — OpenPolicyStack. "
                      "All claims traceable to evidence payload.")
    canvas.drawRightString(w - 1.5*cm, 0.8*cm, f"Page {doc.page}")
    canvas.setStrokeColor(EU_BLUE)
    canvas.setLineWidth(0.5)
    canvas.line(1.5*cm, 1.2*cm, w - 1.5*cm, 1.2*cm)

    canvas.restoreState()


# ─── Page 1: Executive Summary ────────────────────────────────────────────────

# Section headers to detect in the LLM output
SECTION_HEADERS = {
    "context and objective",
    "preferred option and rationale",
    "option comparison summary",
    "evidence quality and assumptions",
}

# Titles to completely skip — redundant with the PDF header
SKIP_TITLES = {
    "eu quantum act options",
    "impact assessment brief: eu quantum act options",
    "impact assessment brief",
    "eu quantum act impact assessment brief",
    "eu quantum act impact assessment brief",
}


def _page1_executive_summary(s, req: BriefRequest, llm_brief: str) -> list:
    story = []

    preferred = next((os for os in req.option_scores if os.rank == 1),
                     req.option_scores[0] if req.option_scores else None)

    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph("Executive Summary", s["title"]))
    story.append(Paragraph(
        f"Scenario: <b>{req.scenario_id}</b> &nbsp;|&nbsp; "
        f"Run ID: <b>{req.run_id}</b> &nbsp;|&nbsp; "
        f"Objective: {req.objective or 'EU Quantum Act option comparison'}",
        s["subtitle"]
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=EU_BLUE, spaceAfter=8))

    # Preferred option highlight box
    if preferred:
        highlight = Table([[
            Paragraph("PREFERRED OPTION", ParagraphStyle(
                "ph", fontSize=8, textColor=WHITE, fontName="Helvetica-Bold")),
            Paragraph(preferred.option_name, ParagraphStyle(
                "pn", fontSize=11, textColor=WHITE, fontName="Helvetica-Bold")),
            Paragraph(f"Score: {preferred.weighted_total:+.3f}", ParagraphStyle(
                "ps", fontSize=11, textColor=EU_GOLD,
                fontName="Helvetica-Bold", alignment=TA_CENTER)),
        ]], colWidths=[3.5*cm, 11*cm, 3*cm])
        highlight.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), EU_BLUE),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",    (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING",   (0, 0), (-1, -1), 12),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
        ]))
        story.append(highlight)
        story.append(Spacer(1, 0.2*cm))

    # Parse LLM brief — clean markdown, detect sections
    clean = _clean_markdown(llm_brief)
    lines = clean.split("\n")

    for line in lines:
        line = line.strip()
        if not line:
            continue

        if line.lower() in SKIP_TITLES:
            continue  # skip redundant LLM title
        elif line.lower() in SECTION_HEADERS:
            story.append(Paragraph(line, s["section"]))
        elif line.startswith("This brief was generated"):
            story.append(Spacer(1, 0.15*cm))
            story.append(HRFlowable(width="100%", thickness=0.5,
                                    color=MID_GREY, spaceAfter=6))
            story.append(Paragraph(line, s["small"]))
        else:
            story.append(Paragraph(line, s["body"]))

    # Option ranking table
    story.append(Spacer(1, 0.15*cm))
    story.append(Paragraph("Option Ranking at a Glance", s["section"]))

    rank_data = [["Rank", "Policy Option", "Score", "Status"]]
    for os in sorted(req.option_scores, key=lambda x: x.rank):
        status_str = str(os.status).replace("OptionStatus.", "").capitalize()
        rank_data.append([str(os.rank), os.option_name,
                          f"{os.weighted_total:+.3f}", status_str])

    rank_table = Table(rank_data, colWidths=[1.5*cm, 10*cm, 2.5*cm, 3.5*cm])
    rank_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), EU_BLUE),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR",     (0, 1), (-1, -1), DARK_GREY),
        ("BACKGROUND",    (0, 1), (-1, 1), EU_BLUE_LIGHT),
        ("ROWBACKGROUNDS",(0, 2), (-1, -1), [WHITE, LIGHT_GREY]),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("ALIGN",         (0, 0), (0, -1), "CENTER"),
        ("ALIGN",         (2, 0), (2, -1), "CENTER"),
    ]))
    story.append(rank_table)
    story.append(Paragraph(
        "Table 1: Ranked policy options under default EU Better Regulation criterion weights.",
        s["caption"]
    ))

    return story


# ─── Page 2: Full MCDA Scoring Table ─────────────────────────────────────────

def _page2_scoring_table(s, req: BriefRequest) -> list:
    story = [PageBreak()]
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph("Full MCDA Scoring Table", s["title"]))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        "Criteria scores for all policy options on the EU Better Regulation anchored scale "
        "(-2 = strongly negative, 0 = neutral, +2 = strongly positive). "
        "Default criterion weights: Economic 0.25, Competitiveness 0.25, Social 0.15, "
        "Feasibility 0.15, Environmental 0.10, Coherence 0.10.",
        s["body"]
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=EU_BLUE, spaceAfter=8))

    criteria    = ["economic", "social", "environmental",
                   "competitiveness", "feasibility", "coherence"]
    crit_labels = ["Econ", "Social", "Env", "Comp", "Feas", "Coh"]

    header     = ["Option"] + crit_labels + ["Total", "Rank"]
    table_data = [header]
    options_sorted = sorted(req.option_scores, key=lambda x: x.rank)

    for os in options_sorted:
        score_map = {cs.criterion: cs.score for cs in os.criteria_scores}
        row = [os.option_name]
        for c in criteria:
            row.append(f"{score_map.get(c, 0.0):+.1f}")
        row.append(f"{os.weighted_total:+.3f}")
        row.append(str(os.rank))
        table_data.append(row)

    col_widths  = [6.5*cm] + [1.5*cm]*6 + [2*cm, 1.2*cm]
    score_table = Table(table_data, colWidths=col_widths)

    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0), EU_BLUE),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR",     (0, 1), (-1, -1), DARK_GREY),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ("BACKGROUND",    (0, 1), (-1, 1), EU_BLUE_LIGHT),
        ("ROWBACKGROUNDS",(0, 2), (-1, -1), [WHITE, LIGHT_GREY]),
    ]

    for row_i, os in enumerate(options_sorted, start=1):
        score_map = {cs.criterion: cs.score for cs in os.criteria_scores}
        for col_i, c in enumerate(criteria, start=1):
            sc = score_map.get(c, 0.0)
            if sc >= 1.5:
                style_cmds.append(("TEXTCOLOR", (col_i, row_i), (col_i, row_i), GREEN))
                style_cmds.append(("FONTNAME",  (col_i, row_i), (col_i, row_i), "Helvetica-Bold"))
            elif sc <= -1.0:
                style_cmds.append(("TEXTCOLOR", (col_i, row_i), (col_i, row_i), RED))
                style_cmds.append(("FONTNAME",  (col_i, row_i), (col_i, row_i), "Helvetica-Bold"))

    score_table.setStyle(TableStyle(style_cmds))
    story.append(score_table)
    story.append(Paragraph(
        "Table 2: Full MCDA criteria scores. Green = strongly positive (+1.5 or above), "
        "Red = strongly negative (-1.0 or below).",
        s["caption"]
    ))

    story.append(Paragraph("Scoring Rationale by Option", s["section"]))

    for os in options_sorted:
        status_str = str(os.status).replace("OptionStatus.", "").capitalize()
        story.append(Paragraph(
            f"<b>{os.option_name}</b> — Score: {os.weighted_total:+.3f} ({status_str})",
            s["preferred"]
        ))
        for cs in os.criteria_scores:
            ev = f"Evidence: {', '.join(cs.evidence_ids)}" if cs.evidence_ids \
                else f"Assumption: {cs.assumption or 'domain knowledge'}"
            story.append(Paragraph(
                f"<b>{cs.criterion.capitalize()}</b> ({cs.score:+.1f}): "
                f"{cs.rationale} <i>[{ev}]</i>",
                s["small"]
            ))
        story.append(Spacer(1, 0.2*cm))

    return story


# ─── Page 3: Evidence & Assumptions ──────────────────────────────────────────

def _page3_evidence(s, req: BriefRequest) -> list:
    story = [PageBreak()]
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph("Evidence & Provenance", s["title"]))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        "All indicators used in scoring are listed below with their source, "
        "quality flag, and value. Quality flags: Verified = official source, "
        "Proxy = estimated fallback, Assumption = no data available.",
        s["body"]
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=EU_BLUE, spaceAfter=8))

    ev_data = [["Indicator", "Source", "Value", "Unit", "Quality"]]
    for e in req.evidence:
        ev_data.append([
            e.indicator_id,
            e.source_ref,
            str(e.value) if e.value is not None else "—",
            e.unit or "—",
            str(e.quality_flag).replace("QualityFlag.", "").capitalize(),
        ])

    ev_table = Table(ev_data, colWidths=[4.2*cm, 4.5*cm, 1.8*cm, 3.2*cm, 2.8*cm])
    ev_style = [
        ("BACKGROUND",    (0, 0), (-1, 0), EU_BLUE),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR",     (0, 1), (-1, -1), DARK_GREY),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT_GREY]),
    ]
    for row_i, e in enumerate(req.evidence, start=1):
        flag = str(e.quality_flag).replace("QualityFlag.", "")
        col  = _quality_color(flag)
        ev_style.append(("TEXTCOLOR", (4, row_i), (4, row_i), col))
        ev_style.append(("FONTNAME",  (4, row_i), (4, row_i), "Helvetica-Bold"))

    ev_table.setStyle(TableStyle(ev_style))
    story.append(ev_table)
    story.append(Paragraph(
        "Table 3: Evidence payload. Every score in Table 2 references at least one "
        "indicator from this table, or carries an explicit assumption tag.",
        s["caption"]
    ))

    story.append(Paragraph("Indicator Notes", s["section"]))
    for e in req.evidence:
        if e.note:
            story.append(Paragraph(
                f"<b>{e.indicator_id}</b>: {e.note}", s["small"]
            ))

    if req.assumptions:
        story.append(Paragraph("Explicit Assumptions", s["section"]))
        story.append(Paragraph(
            "The following criteria scores were assigned without direct indicator "
            "evidence, explicitly flagged in accordance with the "
            "'no evidence → no claim' rule.",
            s["body"]
        ))
        for a in req.assumptions:
            story.append(Paragraph(f"• {a}", s["small"]))

    story.append(Spacer(1, 0.2*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GREY, spaceAfter=8))
    story.append(Paragraph(
        "Methodology: MCDA weighted additive scoring aligned with EU Better Regulation "
        "framework. Criterion weights: Economic 0.25, Competitiveness 0.25, Social 0.15, "
        "Feasibility 0.15, Environmental 0.10, Coherence 0.10. Scoring scale: -2 to +2. "
        "LLM narrative generated by claude-sonnet-4-20250514 constrained to structured inputs only.",
        s["small"]
    ))

    return story


# ─── Master PDF generator ─────────────────────────────────────────────────────

def generate_pdf_brief(req: BriefRequest, llm_brief: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=1.5*cm,
        rightMargin=1.5*cm,
        topMargin=2.5*cm,
        bottomMargin=2*cm,
    )
    s     = _styles()
    story = []
    story += _page1_executive_summary(s, req, llm_brief)
    story += _page2_scoring_table(s, req)
    story += _page3_evidence(s, req)

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buffer.getvalue()